export const permissionModule = [
  { label: "Communications Hub: Internal", key: "communicationHubInternal" },
  { label: "Communications Hub: Clients", key: "communicationHubClients" },
  { label: "Communications Hub: Collaboration", key: "communicationHubCollaboration" },
  { label: "Estimates & Invoices", key: "estimatesInvoices" },
  { label: "Calendar & Task", key: "calendarTask" },
  { label: "Payments", key: "payments" },
  { label: "Workforce Management", key: "workforceManagement", viewOnly: "workforceManagementView" },
  { label: "Reporting & Analytics", key: "reporting", viewOnly: "reportingView" },
  { label: "Inventory", key: "inventory", viewOnly: "inventoryView" },
  { label: "Integrations", key: "integrations" },
  { label: "Sales Pipeline", key: "salesPipeline" },
  { label: "Shop Pipeline", key: "shopPipeline" },
  { label: "Business Settings", key: "businessSettings" },
];
