name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t krshanto/autoworx-next-app:latest \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg AUTH_SECRET=${{ secrets.AUTH_SECRET }} \
            --build-arg PUSHER_ID=${{ secrets.PUSHER_ID }} \
            --build-arg PUSHER_KEY=${{ secrets.PUSHER_KEY }} \
            --build-arg PUSHER_SECRET=${{ secrets.PUSHER_SECRET }} \
            --build-arg PUSHER_CLUSTER=${{ secrets.PUSHER_CLUSTER }} \
            --build-arg NEXT_PUBLIC_PUSHER_KEY=${{ secrets.NEXT_PUBLIC_PUSHER_KEY }} \
            --build-arg NEXT_PUBLIC_PUSHER_CLUSTER=${{ secrets.NEXT_PUBLIC_PUSHER_CLUSTER }} \
            --build-arg NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }} \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --build-arg GMAIL_CLIENT_ID=${{ secrets.GMAIL_CLIENT_ID }} \
            --build-arg GMAIL_CLIENT_SECRET=${{ secrets.GMAIL_CLIENT_SECRET }} \
            --build-arg GMAIL_USER=${{ secrets.GMAIL_USER }} \
            --build-arg GMAIL_PASS=${{ secrets.GMAIL_PASS }} \
            --build-arg TWILIO_SID=${{ secrets.TWILIO_SID }} \
            --build-arg TWILIO_TOKEN=${{ secrets.TWILIO_TOKEN }} \
            --build-arg TWILIO_PHONE=${{ secrets.TWILIO_PHONE }} \
            --build-arg ASANA_PERSONAL_TOKEN=${{ secrets.ASANA_PERSONAL_TOKEN }} \
            --build-arg ASANA_WORKSPACE=${{ secrets.ASANA_WORKSPACE }} \
            --platform linux/amd64 \
            .

          docker push krshanto/autoworx-next-app:latest
