name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Adds the manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker (installs Docker Compose as part of this)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image to Docker Hub using Docker Compose
      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push
