name: TypeScript Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: npm install
        run: npm ci

      - name: npm run tsc
        uses: icrawl/action-tsc@v1
